-- Purchasing Intelligence — device, consent, redacted-event receipt, and
-- config-pack metadata.
--
-- DELIBERATELY NOT A PERSONAL SHOPPING WAREHOUSE. No table here stores cart
-- contents, item names, offer text, URLs, addresses, payment data, cookies,
-- or any account identity. Identity is a pseudonymous device id generated by
-- the local sidecar — never an email.
--
-- Apply locally:  npx wrangler d1 execute <DB> --local  --file=migrations/0002_purchasing_intelligence.sql
-- Apply remotely: npx wrangler d1 execute <DB> --remote --file=migrations/0002_purchasing_intelligence.sql

CREATE TABLE IF NOT EXISTS devices (
  id TEXT PRIMARY KEY,                       -- server-side device id
  pseudonymous_device_id TEXT NOT NULL,      -- sidecar-generated, non-identifying
  device_token_hash TEXT NOT NULL,           -- SHA-256 of the bearer token; never the token itself
  app_version TEXT NOT NULL,
  platform TEXT NOT NULL,
  created_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  deleted_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_devices_pseudonymous
  ON devices(pseudonymous_device_id);
CREATE INDEX IF NOT EXISTS idx_devices_token_hash ON devices(device_token_hash);

CREATE TABLE IF NOT EXISTS consent_receipts (
  id TEXT PRIMARY KEY,                       -- receipt id minted by the sidecar
  device_id TEXT NOT NULL REFERENCES devices(id),
  privacy_mode TEXT NOT NULL,
  consent_version TEXT NOT NULL,
  granted_at TEXT NOT NULL,
  revoked_at TEXT,
  scope_text TEXT NOT NULL,
  app_version TEXT NOT NULL,
  extension_version TEXT,
  received_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_consent_receipts_device ON consent_receipts(device_id);

-- Receipts only: enough to prove an event was accepted and to honor deletion.
-- The bucketed/typed envelope is kept because it is already redacted by
-- construction (see packages/protocol/src/telemetry.ts).
CREATE TABLE IF NOT EXISTS redacted_event_receipts (
  id TEXT PRIMARY KEY,                       -- server receipt id
  event_id TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES devices(id),
  consent_receipt_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  platform TEXT NOT NULL,
  adapter_id TEXT NOT NULL,
  adapter_version TEXT NOT NULL,
  outcome TEXT NOT NULL,
  confidence TEXT NOT NULL,
  subtotal_bucket TEXT,
  offer_type TEXT,
  config_pack_version TEXT,
  occurred_at TEXT NOT NULL,
  received_at TEXT NOT NULL,
  event_integrity_hash TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_redacted_events_event_id
  ON redacted_event_receipts(event_id);
CREATE INDEX IF NOT EXISTS idx_redacted_events_device ON redacted_event_receipts(device_id);

CREATE TABLE IF NOT EXISTS configuration_packs (
  pack_id TEXT PRIMARY KEY,
  description TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS configuration_pack_versions (
  id TEXT PRIMARY KEY,                       -- packId@version
  pack_id TEXT NOT NULL REFERENCES configuration_packs(pack_id),
  version TEXT NOT NULL,
  issued_at TEXT NOT NULL,
  expires_at TEXT,
  rollout_stage TEXT NOT NULL,
  minimum_extension_version TEXT,
  minimum_sidecar_version TEXT,
  key_id TEXT NOT NULL,
  -- The signed pack artifact. Small and public; R2 is the intended home for
  -- larger artifacts once packs grow beyond inline size.
  pack_json TEXT NOT NULL,
  changelog_summary TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pack_versions_pack ON configuration_pack_versions(pack_id, issued_at DESC);

CREATE TABLE IF NOT EXISTS privacy_deletion_requests (
  id TEXT PRIMARY KEY,
  device_id TEXT NOT NULL REFERENCES devices(id),
  pseudonymous_device_id TEXT NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'queued',     -- queued | processed
  requested_at TEXT NOT NULL,
  processed_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_deletion_requests_status
  ON privacy_deletion_requests(status, requested_at);
